---

- hosts: all
  become: true
  tasks:

  - name: update and upgrade the servers
    apt:
      update_cache: yes
      upgrade: yes

  - name: install apache
    apt:
      name: apache2
      state: latest

  - name: set timezone to Africa/lagos
    timezone: name=Africa/Lagos

  - name: print hostname on server
    shell: echo "<h1> My server name is $(hostname -f) and the the time and date in Lagos,Nigeria is $(date)<h1>" > /var/www/html/index.html

  - name: restart apache
    service:
      name: apache2
      status: restarted